
import React from "react";
import { CheckCircle, AlertTriangle, HelpCircle } from "lucide-react";

interface Animal {
  id: number;
  name: string;
  confidence: number;
  status: "alive" | "dead" | "unknown";
}

interface DetectionResultsProps {
  animals: Animal[];
  isLoading?: boolean;
}

const DetectionResults: React.FC<DetectionResultsProps> = ({
  animals,
  isLoading = false,
}) => {
  if (isLoading) {
    return (
      <div className="glass-card rounded-xl p-6 h-full">
        <h3 className="text-xl font-bold text-white mb-4">Detection Results</h3>
        <div className="flex flex-col items-center justify-center py-12">
          <div className="w-12 h-12 border-4 border-wildlife-blue border-t-transparent rounded-full animate-spin"></div>
          <p className="mt-4 text-gray-400">Processing...</p>
        </div>
      </div>
    );
  }

  if (animals.length === 0) {
    return (
      <div className="glass-card rounded-xl p-6 h-full">
        <h3 className="text-xl font-bold text-white mb-4">Detection Results</h3>
        <div className="flex flex-col items-center justify-center py-12 text-gray-400">
          <HelpCircle className="w-12 h-12 mb-3" />
          <p>No animals detected yet</p>
          <p className="text-sm mt-2">Upload an image or video to begin</p>
        </div>
      </div>
    );
  }

  return (
    <div className="glass-card rounded-xl p-6 h-full">
      <h3 className="text-xl font-bold text-white mb-4">Detection Results</h3>
      
      <div className="space-y-4">
        {animals.map((animal) => (
          <div
            key={animal.id}
            className="bg-gray-800/50 rounded-lg p-4 border border-gray-700"
          >
            <div className="flex justify-between items-center mb-2">
              <h4 className="font-medium text-white">{animal.name}</h4>
              <span
                className={`px-2 py-1 rounded text-xs font-medium ${
                  animal.status === "alive"
                    ? "bg-green-500/20 text-green-400"
                    : animal.status === "dead"
                    ? "bg-red-500/20 text-red-400"
                    : "bg-yellow-500/20 text-yellow-400"
                }`}
              >
                {animal.status.toUpperCase()}
              </span>
            </div>
            
            <div className="w-full bg-gray-700 rounded-full h-2.5 mb-2">
              <div
                className={`h-2.5 rounded-full ${
                  animal.confidence > 80
                    ? "bg-green-500"
                    : animal.confidence > 50
                    ? "bg-yellow-500"
                    : "bg-red-500"
                }`}
                style={{ width: `${animal.confidence}%` }}
              ></div>
            </div>
            
            <div className="flex justify-between">
              <span className="text-xs text-gray-400">Confidence</span>
              <span className="text-xs font-medium text-gray-300">
                {animal.confidence}%
              </span>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 pt-4 border-t border-gray-700">
        <div className="flex items-start">
          <AlertTriangle className="text-yellow-500 mr-2 mt-0.5" size={16} />
          <p className="text-sm text-yellow-300">
            In a production environment, this data would be generated by Python-based 
            machine learning models running on a backend server.
          </p>
        </div>
      </div>
    </div>
  );
};

export default DetectionResults;
